### PR TITLE
Embedded can dev

### PR DESCRIPTION
**Pull request by ezraboley**
Basic CAN RX/TX. Additional functionality could be added (timeouts for example), but the framework is there and it works. Also added a tests folder where module level testing can be added.

### CODE REVIEW

**Comment by ezraboley** [comment]
It is currently configured for vcan0, which is useful for testing CAN but the final interface will likely be changed to can0 or can1

**Comment by rdaruwala** [comment]
Looks like a great start to me. Has it been tested with current hardware as of yet?

May want to consider adding a README so it's simple for anyone (Especially those who aren't as familiar with CAN) to setup / use the interface

**Comment by ezraboley** [comment]
Good idea, I'll toss one up! It hasn't been tested on the hardware, but it is written using the SocketCAN API on a virtual instance of CAN, so the only change that would need to be made is to change vcan0 to can0. For this implementation, the hardware is abstracted away so it should "just work", even if those are famous last words.

**Review by rdaruwala — APPROVED** [review]
Sounds good! Looks like a great start for CAN. Excited to test it out

**Pull request merged**
