### PR TITLE
Embedded restructure

### PR DESCRIPTION
**Pull request by ezraboley**
Just changing the folder structure around a little. No content changed

### CODE REVIEW

**Review by rdaruwala — CHANGES_REQUESTED** [review]
We'll want to change the header filepaths in the different files as they likely now point to invalid locations

Optionally consider changing the folder name "h" to something like "include". A one letter folder name seems a bit weird to me, but that's just my personal 2c

**Comment by ezraboley** [comment]
Sure, I'll change the names and paths and push that commit before merging

**Comment by ezraboley** [comment]
All the requested changes should be pushed if you want to give it another look, it'd be good to have this squared away before we get new members on board

**Review by rdaruwala — APPROVED** [review]

**Comment by rdaruwala** [comment]
Merged the branch, but we'll want to keep working on this. Now that we've separated the dashboard, let's consider moving the Makefile to the repository root directory so we can better access the middleware software as well

**Pull request merged**
