### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ezraboley**

### CODE REVIEW

**Comment by EUdds** [comment]
Can't approve... you were doing this instead of listening to the NodeJs seminar

**Review by rdaruwala — CHANGES_REQUESTED** [review]
Not sure if you're trying to embed the image, or sneak that link in, or...

But it should probably be prettied up a little before hitting master

**Comment by ezraboley** [comment]
My b! I guess I grabbed the wrong snippet from their website. Should look good now

**Review by rdaruwala — APPROVED** [review]
Love it! Also added my own small edit

**Pull request merged**
